Models/Employee.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication3MVC.Models
{

    [Index(nameof(nom), nameof(prenom), Name = "IX_Employee", IsUnique = false)]
    public class Employee
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Nom Employé")]
        [StringLength(20)]
        [Column(TypeName = "varchar")]
        public string nom { get; set; }
        [Display(Name = "Prénom Employé")]
        [StringLength(20)]
        public string prenom { get; set; }
        [Display(Name = "Date Entrée")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? DateEntree { get; set; }



        private decimal? _CA = 0;
        [Display(Name = "Chiffre d'affaire")]
        [DisplayFormat(DataFormatString = "{0:# ##0.00 €}")]
        [Column(TypeName = "decimal(16,2)")]
        public decimal? CA
        {
            get => _CA ?? 0;
            set => _CA = value;
        }
    }
}
        

Models/ErrorViewModel.cs
using System;

namespace WebApplication3MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication3MVC.Data;
using WebApplication3MVC.Models;

namespace WebApplication3MVC.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {

            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {

            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,nom,prenom,DateEntree,CA")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,nom,prenom,DateEntree,CA")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3MVC.Models;

namespace WebApplication3MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TotoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication3MVC.Models;

namespace WebApplication3MVC.Controllers
{
    public class TotoController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "TEST TITLE SUPER";
            return View();
        }

        public IActionResult Autre()
        {
            ViewData["Title"] = "TEST Autre SUPER";
            return View("Index");
        }

        public IActionResult Employee()

        {
            Employee emp1 = new()
            {
                nom = "telouk",
                prenom = "Vincent"
            };

            return View(emp1);
        }
    }
}

Views/Employees/Create.cshtml
@model WebApplication3MVC.Models.Employee

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nom" class="control-label"></label>
                <input asp-for="nom" class="form-control" />
                <span asp-validation-for="nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prenom" class="control-label"></label>
                <input asp-for="prenom" class="form-control" />
                <span asp-validation-for="prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEntree" class="control-label"></label>
                <input asp-for="DateEntree" class="form-control" />
                <span asp-validation-for="DateEntree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CA" class="control-label"></label>
                <input asp-for="CA" class="form-control" />
                <span asp-validation-for="CA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Employees/Delete.cshtml
@model WebApplication3MVC.Models.Employee

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEntree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEntree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CA)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Employees/Details.cshtml
@model WebApplication3MVC.Models.Employee

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEntree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEntree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CA)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CA)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Employees/Edit.cshtml
@model WebApplication3MVC.Models.Employee

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="nom" class="control-label"></label>
                <input asp-for="nom" class="form-control" />
                <span asp-validation-for="nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="prenom" class="control-label"></label>
                <input asp-for="prenom" class="form-control" />
                <span asp-validation-for="prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEntree" class="control-label"></label>
                <input asp-for="DateEntree" class="form-control" />
                <span asp-validation-for="DateEntree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CA" class="control-label"></label>
                <input asp-for="CA" class="form-control" />
                <span asp-validation-for="CA" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Employees/Index.cshtml
@model IEnumerable<WebApplication3MVC.Models.Employee>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateEntree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CA)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateEntree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CA)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Toto" asp-action="Index">Toto</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication3MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Toto/Employee.cshtml
@model WebApplication3MVC.Models.Employee

<h1>Details de l'employez</h1>
<p>@Html.DisplayNameFor(m => m.nom) : @Html.DisplayFor(_ => Model.nom)</p>
<p>@Html.DisplayNameFor(m => m.prenom) : @Html.DisplayFor(_ => Model.prenom)</p>
<p>@Html.DisplayNameFor(m => m.CA) : @Html.DisplayFor(_ => Model.CA)</p>
<p>@Html.DisplayNameFor(m => m.DateEntree) : @Html.DisplayFor(_ => Model.DateEntree)</p>

Views/Toto/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>
    Titre : @ViewData["Title"]
</h1>

<p>
    testtsetseesttesteststst
</p>